main/templates/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('index', views.index, name='index_page'),
    path('login', views.login_view, name='login_page'),
    path('products', views.products_page, name='product_page'),
    path('products/create', views.product_create, name='product_create_page'),
    path('products/<int:id>', views.product_detail, name='product_detail_page'),
    path('products/brand/<int:id>', views.brand_products, name='brand_products'),
    path('brands', views.brand_view, name='brands_page'),
    path('cabinet', views.cabinet, name='cabinet'),
    path('logout', views.logout_view, name='logout_view'),
    path('reqister', views.reqister_view, name='reqister_view'),
]

your_sneakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

class CostType(models.Model):
    name = models.CharField(max_length=100, verbose_name='ТИП')

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название брэнда')

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название продукта')
    cost = models.FloatField(verbose_name='Цена')
    cost_type = models.ForeignKey(CostType, null=True, on_delete=models.SET_NULL)
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(null=True, default=None)
    brand = models.ForeignKey(Brand, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name + ": " + str(self.cost) + " " + self.cost_type.name

main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
# Create your views here.
def index(request):
    user = 'test'
    return render(request, 'main/index.html', {'user': user})


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        user = authenticate(request, username=username, password=password)
        if user != None:
            login(request, user)
            return redirect(reverse('main:cabinet', args=()))
        else:
            return redirect(reverse('main:login_page', args=()))
    return render(request, 'main/login.html', {})



def cabinet(request):
    if request.user.is_authenticated:
        return render(request, 'main/cabinet.html', {})
    else:
        return redirect(reverse('main:login_page', args=()))


def logout_view(request):
    logout(request)
    return redirect(reverse('main:login_page', args=()))

def reqister_view(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        email = request.POST.get('email', None)
        firstname = request.POST.get('firstname', None)
        lastname = request.POST.get('lastname', None)
        group_id = request.POST.get('group')
        group = Group.objects.get(id=group_id)
        user = User.objects.create_user(
            username=username,
            email=email,
            first_name=firstname,
            last_name=lastname
        )
        user.set_password(password)
        user.groups.add(group)
        user.save()
        return redirect(reverse('main:login_page', args=()))
    groups = Group.objects.all()
    return render(request, 'main/register_page.html', {'groups': groups})


def products_page(request):
    products = models.Product.objects.all()
    return render(request, 'main/products.html', {'products': products})



def product_create(request):

    if request.method == "POST":
        name = request.POST.get("name")
        description = request.POST.get("description")
        cost = request.POST.get("cost")
        cost_type = models.CostType.objects.get(id=request.POST.get("cost_type"))
        image = request.FILES.get("image")
        print(image)
        product = models.Product(
        name=name,
        description=description,
        cost=float(cost),
        cost_type=cost_type,
        image=image
        )
        product.save()
        return redirect(reverse('main:product_page', args=()))
    else:
        options = models.CostType.objects.all()
        return render(request, "main/product_create.html", {'options': options})

def product_detail(request, id):
    product = models.Product.objects.get(id=id)
    return render(request, "main/product_detail.html", {"product": product})

def brand_products(request, id):
    products = models.Product.objects.filter(brand__id=id)
    return render(request, 'main/products.html', {'products': products})

def brand_view(request):
    brands = models.Brand.objects.all()
    return render(request, 'main/brands.html', {'brands': brands})

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %}  {% endblock %}</title>
  </head>
  <body class="container-fluid">
    {% block body  %} {% endblock %}
  </body>
</html>

main/templates/main/brands.html
{% extends 'main/base.html' %}

{% block title %}
Products Page
{% endblock %}

{% block body %}

  {% include "main/navigation_bar.html" %}

  <div class="row">
    <div class="col-sm-12">
      {% if brands %}
      <table>
        <thead>
          <tr>
            <td>Название</td>
        </thead>
        <tbody>
          {% for b in brands %}
          <tr>
            <td><a href="{% url 'main:brand_products' b.id %}">{{ b.name }}</a></td>

          </tr>
          {% endfor %}
        </tbody>



      </table>

      {% else %}
        <p>Пока, что нет товаров</p>
        {% endif %}
    </div>

  </div>

 {% endblock %}

main/templates/main/cabinet.html
{% extends 'main/base.html' %}

{% block title %} Index Page {% endblock %}

{% block body %}
  {% include 'main/navigation_bar.html' %}

   <div class="row mt-4 pt-4">
     <div class="col-sm-12">
       <h1>Hello, {{ user.username }}</h1>
       <h1>Is stuff? {{ user.is_staff }}</h1>
       <h1>Is superuser? {{ user.is_superuser }}</h1>

     </div>

   </div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %} Index Page {% endblock %}

{% block body %}
  {% include 'main/navigation_bar.html' %}

 <div class="row">
    <div class="col-sm-12">
      <div class="jumbotron">
       <h1>your_sneakers</h1>
       <p>One of the best online stores in Almaty, luxury quality, cooperation with the largest companies</p>
     </div>
   </div>
 </div>
<div class="row">
  <div class="col-sm-6">
    <h1 class="dicplay-4">Online Store</h1>
    <p>your_sneakers store is the largest online store in Almaty, selling only quality goods. for all questions, contact whatsapp +77714550044 </p>
    </div>
    <div class="col-sm-6">
      <img src="{% static 'main/sneakers.jpg' %}" alt="Shop Logo">
     </<div>
   </div>
   <div class="row mt-4">

     <div class="col-sm-12">
       <h1 class="dicplay-4" >your_sneakers</h1>
       <p>Online purchase of sneakers from top brands in our store is an opportunity to receive an order anywhere in the country as soon as possible, take a neighboring size to try on, and not overpay for delivery from abroad</p>
     </div>
    <div class="row mt-4">
      <div class="col-sm-12">
         <img src="{% static 'main/Online_Store.jpg' %}" alt="Online Store">
      </div>


    </div>

{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %} Index Page {% endblock %}

{% block body %}
  {% include 'main/navigation_bar.html' %}

   <div class="row mt-4 pt-4">
     <div class="col-sm-12">
       <form class="w-25 mx-auto" method="post">
         {% csrf_token %}
         <input type="text" name="username" class="form-control w-75 mx-auto mt-4" placeholder="Введите имя пользователя">
         <input type="password" name="password" class="form-control w-75 mx-auto mt-4" placeholder="Введите пароль">
         <input type="submit" class="w-75 mx-auto mt-4 form-control bg-primary " name="login" value="Войти">
      </form>

     </div>

   </div>

{% endblock %}

main/templates/main/navigation_bar.html
<div class="row">
  <div class="col-sm-12">
    <nav class="navbar navbar-expand-sm bg-light">

      <!-- Links -->
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:logout_view' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:login_page' %}">Login Page</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:reqister_view' %}">Reqister Page</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:product_page' %}">Products Page</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:product_create_page' %}">Products Create Page</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:brands_page' %}">All Brands Page</a>
        </li>
      </ul>

    </nav>

  </div>

</div>

main/templates/main/product_create.html
{% extends 'main/base.html' %}

{% block title %} Create Product Page {% endblock %}

{% block body %}
  {% include 'main/navigation_bar.html' %}

  <div class="row">
    <div class="col-sm-12">
      <form class="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="name" placeholder="Название">
        <input type="text" name="description" placeholder="Описание">
        <input type="" name="cost" placeholder="Цена">
        <select class="" name="cost_type">
          {% for o in options %}
          <option value="{{ o.id }}">{{ o.name }}</option>
          {% endfor %}

        </select>
        <input type="file" name="image">
        <input type="submit" name="submit" value="Add new Product">
      </form>
    </div>
  </div>
{% endblock %}

main/templates/main/product_detail.html
{% extends 'main/base.html' %}

{% block title %} Create Product Page {% endblock %}

{% block body %}
  {% include 'main/navigation_bar.html' %}

  <div class="row">
    <div class="col-sm-6">
      <img src="{{MEDIA_URL}}{{product.image}}" alt="Product Image">
        </div>
    <div class="col-sm-6">
      <table>
        <tr>
          <td>Название</td>
          <td>{{ product.name }}</td>
        </tr>
        <tr>
          <td>Описание</td>
          <td>{{ product.description }}</td>
        </tr>
        <tr>
          <td>Цена</td>
          <td>{{ product.cost }} {{ product.cost_type.name }}</td>
        </tr>
      </table>

    </div>
  </div>
{% endblock %}

main/templates/main/products.html
{% extends 'main/base.html' %}

{% block title %}
Products Page
{% endblock %}

{% block body %}

  {% include "main/navigation_bar.html" %}

  <div class="row">
    <div class="col-sm-12">
      {% if products %}
      <table>
        <thead>
          <tr>
            <td>Название</td>
            <td>Описание</td>
            <td>Цена</td>
            <td>Картинка</td>
            <td>Brand</td>
        </thead>
        <tbody>
          {% for p in products %}
          <tr>
            <td><a href="{% url 'main:product_detail_page' p.id %}">{{ p.name }}</a></td>
            <td>{{ p.description }}</td>
            <td>{{ p.cost }} {{ p.cost_type.name }}</td>
            <td><img src="{{MEDIA_URL}}{{p.image}}" alt=""></td>
            <td>{{ p.brand.name }}</td>
          </tr>
          {% endfor %}
        </tbody>



      </table>

      {% else %}
        <p>Пока, что нет товаров</p>
        {% endif %}
    </div>

  </div>

 {% endblock %}

main/templates/main/register_page.html
{% extends 'main/base.html' %}

{% block title %} Index Page {% endblock %}

{% block body %}
  {% include 'main/navigation_bar.html' %}

   <div class="row mt-4 pt-4">
     <div class="col-sm-12">
       <form class="w-25 mx-auto" method="post">
         {% csrf_token %}
         <input type="text" name="username" class="form-control w-75 mx-auto mt-4" placeholder="Введите имя пользователя">
         <input type="password" name="password" class="form-control w-75 mx-auto mt-4" placeholder="Введите пароль">
         <input type="email" name="email" class="form-control w-75 mx-auto mt-4" placeholder="Введите почту">
         <input type="password" name="firstname" class="form-control w-75 mx-auto mt-4" placeholder="Введите имя">
         <input type="password" name="lastname" class="form-control w-75 mx-auto mt-4" placeholder="Введите фамилию">
         <select class="form-control w-75 mx-auto mt-4" name="group">
           <option disabled selected>Select group</option>
           {% for g in groups %}
             <option value="{{ g.id }}">{{ g.name }}</option>
           {% endfor %}
         </select>
         <input type="submit" class="w-75 mx-auto mt-4 form-control bg-primary " name="login" value="Войти">
      </form>

     </div>

   </div>

{% endblock %}